
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Module
{
/// <summary>
/// 界面UI-01
/// </summary>
public partial class TbUIData
{
    private readonly System.Collections.Generic.Dictionary<int, Module.UIData> _dataMap;
    private readonly System.Collections.Generic.List<Module.UIData> _dataList;
    
    public TbUIData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Module.UIData>(count);
        _dataList = new System.Collections.Generic.List<Module.UIData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Module.UIData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Config.Module.UIData.DeserializeUIData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Module.UIData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Module.UIData> DataList => _dataList;

    public Module.UIData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Module.UIData Get(int key) => _dataMap[key];
    public Module.UIData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

