
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Module
{
public sealed partial class UIData : Luban.BeanBase
{
    public UIData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["asset"].IsString) { throw new SerializationException(); }  Asset = _buf["asset"]; }
        { if(!_buf["sorting_layer"].IsString) { throw new SerializationException(); }  SortingLayer = _buf["sorting_layer"]; }
        { if(!_buf["order_in_layer"].IsNumber) { throw new SerializationException(); }  OrderInLayer = _buf["order_in_layer"]; }
    }

    public static UIData DeserializeUIData(JSONNode _buf)
    {
        return new Module.UIData(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 资产
    /// </summary>
    public readonly string Asset;
    /// <summary>
    /// 显示层级
    /// </summary>
    public readonly string SortingLayer;
    /// <summary>
    /// 层级中顺序
    /// </summary>
    public readonly short OrderInLayer;
   
    public const int __ID__ = -2120523264;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "asset:" + Asset + ","
        + "sortingLayer:" + SortingLayer + ","
        + "orderInLayer:" + OrderInLayer + ","
        + "}";
    }
}
}

