
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Battle
{ 
    public enum Attribute
    {
        /// <summary>
        /// 生命
        /// </summary>
        health = 1,
        /// <summary>
        /// 攻击
        /// </summary>
        attack = 2,
    }

} 

