
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Battle
{
public sealed partial class BuffData : Luban.BeanBase
{
    public BuffData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["order"].IsNumber) { throw new SerializationException(); }  Order = _buf["order"]; }
        { if(!_buf["maxStack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["maxStack"]; }
    }

    public static BuffData DeserializeBuffData(JSONNode _buf)
    {
        return new Battle.BuffData(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    public readonly int Order;
    public readonly int MaxStack;
   
    public const int __ID__ = -833855725;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "order:" + Order + ","
        + "maxStack:" + MaxStack + ","
        + "}";
    }
}
}

