
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Battle
{
public sealed partial class BuffData : Luban.BeanBase
{
    public BuffData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["effects"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Effects = new string[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Effects[__index0++] = __v0; }   }
        { var __json0 = _buf["parametric"]; if(!__json0.IsArray) { throw new SerializationException(); } Parametric = new System.Collections.Generic.Dictionary<Battle.BuffParam, float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Battle.BuffParam _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = (Battle.BuffParam)__e0[0].AsInt; } float _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Parametric.Add(_k0, _v0); }   }
    }

    public static BuffData DeserializeBuffData(JSONNode _buf)
    {
        return new Battle.BuffData(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    public readonly string[] Effects;
    /// <summary>
    /// Buff参数
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<Battle.BuffParam, float> Parametric;
   
    public const int __ID__ = -833855725;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "parametric:" + Luban.StringUtil.CollectionToString(Parametric) + ","
        + "}";
    }
}
}

