
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Battle
{ 
    public enum BuffParam
    {
        /// <summary>
        /// 初始层数
        /// </summary>
        StartStack = 1,
        /// <summary>
        /// 计时
        /// </summary>
        TimerDuration = 2,
    }

} 

