
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Battle
{ 
    public enum DamageSource
    {
        /// <summary>
        /// 主要伤害
        /// </summary>
        Main = 1,
        /// <summary>
        /// 派生伤害
        /// </summary>
        Derivation = 2,
        /// <summary>
        /// 反弹伤害
        /// </summary>
        Bounce = 3,
    }

} 

