
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Battle
{
public sealed partial class EffectAttack : Battle.EffectParamBase
{
    public EffectAttack(JSONNode _buf)  : base(_buf) 
    {
    }

    public static EffectAttack DeserializeEffectAttack(JSONNode _buf)
    {
        return new Battle.EffectAttack(_buf);
    }

   
    public const int __ID__ = -116374353;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

