
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Battle
{
public sealed partial class EffectData : Luban.BeanBase
{
    public EffectData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["tag"].IsString) { throw new SerializationException(); }  Tag = _buf["tag"]; }
        { if(!_buf["luaScript"].IsString) { throw new SerializationException(); }  LuaScript = _buf["luaScript"]; }
    }

    public static EffectData DeserializeEffectData(JSONNode _buf)
    {
        return new Battle.EffectData(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    public readonly string Tag;
    /// <summary>
    /// lua脚本
    /// </summary>
    public readonly string LuaScript;
   
    public const int __ID__ = -1702841391;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tag:" + Tag + ","
        + "luaScript:" + LuaScript + ","
        + "}";
    }
}
}

