
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Battle
{
public sealed partial class EffectData : Luban.BeanBase
{
    public EffectData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["order"].IsNumber) { throw new SerializationException(); }  Order = _buf["order"]; }
        { if(!_buf["luaScript"].IsString) { throw new SerializationException(); }  LuaScript = _buf["luaScript"]; }
        { if(!_buf["parameters"].IsObject) { throw new SerializationException(); }  Parameters = global::Game.Config.Battle.EffectParamBase.DeserializeEffectParamBase(_buf["parameters"]);  }
    }

    public static EffectData DeserializeEffectData(JSONNode _buf)
    {
        return new Battle.EffectData(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 执行优先级
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// lua脚本
    /// </summary>
    public readonly string LuaScript;
    public readonly Battle.EffectParamBase Parameters;
   
    public const int __ID__ = -1702841391;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Parameters?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "order:" + Order + ","
        + "luaScript:" + LuaScript + ","
        + "parameters:" + Parameters + ","
        + "}";
    }
}
}

