
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Battle
{
/// <summary>
/// 增减益Buff-02
/// </summary>
public partial class TbBuffData
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.BuffData> _dataMap;
    private readonly System.Collections.Generic.List<Battle.BuffData> _dataList;
    
    public TbBuffData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.BuffData>(count);
        _dataList = new System.Collections.Generic.List<Battle.BuffData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.BuffData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Config.Battle.BuffData.DeserializeBuffData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Battle.BuffData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Battle.BuffData> DataList => _dataList;

    public Battle.BuffData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Battle.BuffData Get(int key) => _dataMap[key];
    public Battle.BuffData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

