
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    public enum Accessory
    {
        /// <summary>
        /// 项链
        /// </summary>
        Necklace = 1,
        /// <summary>
        /// 手环
        /// </summary>
        Bracelet = 2,
        /// <summary>
        /// 戒指
        /// </summary>
        Ring = 3,
    }

} 

