
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    public enum ArmorLevel
    {
        /// <summary>
        /// 布甲
        /// </summary>
        Cloth = 1,
        /// <summary>
        /// 皮甲
        /// </summary>
        Leather = 2,
        /// <summary>
        /// 链甲
        /// </summary>
        Chain = 3,
        /// <summary>
        /// 板甲
        /// </summary>
        Plate = 4,
    }

} 

