
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    public enum ArmorSlot
    {
        /// <summary>
        /// 头
        /// </summary>
        Head = 1,
        /// <summary>
        /// 身
        /// </summary>
        Chest = 2,
        /// <summary>
        /// 手
        /// </summary>
        Hands = 3,
        /// <summary>
        /// 腿
        /// </summary>
        Legs = 4,
        /// <summary>
        /// 脚
        /// </summary>
        Feet = 5,
    }

} 

