
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    public enum BaseAttribute
    {
        /// <summary>
        /// 力量
        /// </summary>
        Strength = 1,
        /// <summary>
        /// 智力
        /// </summary>
        Intelligence = 2,
        /// <summary>
        /// 敏捷
        /// </summary>
        Dexterity = 3,
        /// <summary>
        /// 体质
        /// </summary>
        Constitution = 4,
        /// <summary>
        /// 精神
        /// </summary>
        Spirit = 5,
        /// <summary>
        /// 感知
        /// </summary>
        Wisdom = 6,
    }

} 

