
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Character
{
public partial class BaseEquipmentData
{
    private readonly System.Collections.Generic.List<Character.TbBaseEquipmentData> _dataList;

    private System.Collections.Generic.Dictionary<int, Character.TbBaseEquipmentData> _dataMap_id;
    private System.Collections.Generic.Dictionary<int, Character.TbBaseEquipmentData> _dataMap_base_type;

    public BaseEquipmentData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<Character.TbBaseEquipmentData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Character.TbBaseEquipmentData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Config.Character.TbBaseEquipmentData.DeserializeTbBaseEquipmentData(_ele);  }
            _dataList.Add(_v);
        }
        _dataMap_id = new System.Collections.Generic.Dictionary<int, Character.TbBaseEquipmentData>(count);
        _dataMap_base_type = new System.Collections.Generic.Dictionary<int, Character.TbBaseEquipmentData>(count);
        foreach(var _v in _dataList)
        {
            _dataMap_id.Add(_v.Id, _v);
            _dataMap_base_type.Add(_v.BaseType, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<Character.TbBaseEquipmentData> DataList => _dataList;

    public Character.TbBaseEquipmentData GetById(int key) => _dataMap_id.TryGetValue(key, out Character.TbBaseEquipmentData __v) ? __v : default;
    public Character.TbBaseEquipmentData GetByBaseType(int key) => _dataMap_base_type.TryGetValue(key, out Character.TbBaseEquipmentData __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

