
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Character
{
public partial class ClassData
{
    private readonly System.Collections.Generic.List<Character.TbClassData> _dataList;

    private System.Collections.Generic.Dictionary<int, Character.TbClassData> _dataMap_id;
    private System.Collections.Generic.Dictionary<Character.SubClass, Character.TbClassData> _dataMap_type;

    public ClassData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<Character.TbClassData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Character.TbClassData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Config.Character.TbClassData.DeserializeTbClassData(_ele);  }
            _dataList.Add(_v);
        }
        _dataMap_id = new System.Collections.Generic.Dictionary<int, Character.TbClassData>(count);
        _dataMap_type = new System.Collections.Generic.Dictionary<Character.SubClass, Character.TbClassData>(count);
        foreach(var _v in _dataList)
        {
            _dataMap_id.Add(_v.Id, _v);
            _dataMap_type.Add(_v.Type, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<Character.TbClassData> DataList => _dataList;

    public Character.TbClassData GetById(int key) => _dataMap_id.TryGetValue(key, out Character.TbClassData __v) ? __v : default;
    public Character.TbClassData GetByType(Character.SubClass key) => _dataMap_type.TryGetValue(key, out Character.TbClassData __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

