
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Character
{
public partial class LvData
{
    private readonly System.Collections.Generic.List<Character.TbLvData> _dataList;

    private System.Collections.Generic.Dictionary<int, Character.TbLvData> _dataMap_id;
    private System.Collections.Generic.Dictionary<int, Character.TbLvData> _dataMap_lv;

    public LvData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<Character.TbLvData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Character.TbLvData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Config.Character.TbLvData.DeserializeTbLvData(_ele);  }
            _dataList.Add(_v);
        }
        _dataMap_id = new System.Collections.Generic.Dictionary<int, Character.TbLvData>(count);
        _dataMap_lv = new System.Collections.Generic.Dictionary<int, Character.TbLvData>(count);
        foreach(var _v in _dataList)
        {
            _dataMap_id.Add(_v.Id, _v);
            _dataMap_lv.Add(_v.Lv, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<Character.TbLvData> DataList => _dataList;

    public Character.TbLvData GetById(int key) => _dataMap_id.TryGetValue(key, out Character.TbLvData __v) ? __v : default;
    public Character.TbLvData GetByLv(int key) => _dataMap_lv.TryGetValue(key, out Character.TbLvData __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

