
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    public enum MainClass
    {
        /// <summary>
        /// 战士
        /// </summary>
        Warrior = 1,
        /// <summary>
        /// 法师
        /// </summary>
        Mage = 2,
        /// <summary>
        /// 牧师
        /// </summary>
        Priest = 3,
        /// <summary>
        /// 猎人
        /// </summary>
        Hunter = 4,
    }

} 

