
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Character
{
public sealed partial class ParamDefine : Luban.BeanBase
{
    public ParamDefine(JSONNode _buf) 
    {
        { var __json0 = _buf["baseValue"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; BaseValue = new float[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BaseValue[__index0++] = __v0; }   }
        { if(!_buf["format"].IsString) { throw new SerializationException(); }  Format = _buf["format"]; }
    }

    public static ParamDefine DeserializeParamDefine(JSONNode _buf)
    {
        return new Character.ParamDefine(_buf);
    }

    public readonly float[] BaseValue;
    public readonly string Format;
   
    public const int __ID__ = -1909754589;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "baseValue:" + Luban.StringUtil.CollectionToString(BaseValue) + ","
        + "format:" + Format + ","
        + "}";
    }
}
}

