
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    public enum SubClass
    {
        /// <summary>
        /// 血刃掠夺者
        /// </summary>
        BloodBladeRaider = 101,
        /// <summary>
        /// 铁壁卫将
        /// </summary>
        IronwallGuardian = 102,
        /// <summary>
        /// 裂阵勇士
        /// </summary>
        LineBreaker = 103,
        /// <summary>
        /// 焚界术士
        /// </summary>
        WorldBurner = 201,
        /// <summary>
        /// 奥术织构者
        /// </summary>
        ArcaneWeaver = 202,
        /// <summary>
        /// 寒霜秘术师
        /// </summary>
        FrostArcanist = 203,
        /// <summary>
        /// 圣裁者
        /// </summary>
        DivineJudge = 301,
        /// <summary>
        /// 守护神官
        /// </summary>
        GuardianPriest = 302,
        /// <summary>
        /// 净罪使徒
        /// </summary>
        Purifier = 303,
        /// <summary>
        /// 森林之子
        /// </summary>
        ChildOfTheForest = 401,
        /// <summary>
        /// 暗影猎手
        /// </summary>
        ShadowHunter = 402,
        /// <summary>
        /// 双刃
        /// </summary>
        BladeDancer = 403,
    }

} 

