
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    public enum TalentType
    {
        /// <summary>
        /// 被动
        /// </summary>
        Passive = 1,
        /// <summary>
        /// 主动
        /// </summary>
        Active = 2,
    }

} 

