
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Character
{
public sealed partial class TalentData : Luban.BeanBase
{
    public TalentData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (Character.TalentType)_buf["type"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["desc_params"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; DescParams = new Character.ParamDefine[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Character.ParamDefine __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::Game.Config.Character.ParamDefine.DeserializeParamDefine(__e0);  }  DescParams[__index0++] = __v0; }   }
    }

    public static TalentData DeserializeTalentData(JSONNode _buf)
    {
        return new Character.TalentData(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    public readonly Character.TalentType Type;
    public readonly string Desc;
    /// <summary>
    /// baseValue
    /// </summary>
    public readonly Character.ParamDefine[] DescParams;
   
    public const int __ID__ = 907398875;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in DescParams) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "desc:" + Desc + ","
        + "descParams:" + Luban.StringUtil.CollectionToString(DescParams) + ","
        + "}";
    }
}
}

