
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Character
{
public sealed partial class TbBaseEquipmentData : Luban.BeanBase
{
    public TbBaseEquipmentData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["base_type"].IsNumber) { throw new SerializationException(); }  BaseType = _buf["base_type"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
    }

    public static TbBaseEquipmentData DeserializeTbBaseEquipmentData(JSONNode _buf)
    {
        return new Character.TbBaseEquipmentData(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Character.Weapon
    /// </summary>
    public readonly int BaseType;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = -943211596;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "baseType:" + BaseType + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

