
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Character
{
public sealed partial class TbClassData : Luban.BeanBase
{
    public TbClassData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["main_type"].IsNumber) { throw new SerializationException(); }  MainType = (Character.MainClass)_buf["main_type"].AsInt; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (Character.SubClass)_buf["type"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["weapon_unlock"].IsNumber) { throw new SerializationException(); }  WeaponUnlock = (Character.Weapon)_buf["weapon_unlock"].AsInt; }
        { var __json0 = _buf["talent_tree"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; TalentTree = new int[_n0][]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int[] __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } int _n1 = __json1.Count; __v0 = new int[_n1]; int __index1=0; foreach(JSONNode __e1 in __json1.Children) { int __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0[__index1++] = __v1; }   }  TalentTree[__index0++] = __v0; }   }
    }

    public static TbClassData DeserializeTbClassData(JSONNode _buf)
    {
        return new Character.TbClassData(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 主职业
    /// </summary>
    public readonly Character.MainClass MainType;
    /// <summary>
    /// 子职
    /// </summary>
    public readonly Character.SubClass Type;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 武器擅长
    /// </summary>
    public readonly Character.Weapon WeaponUnlock;
    public readonly int[][] TalentTree;
   
    public const int __ID__ = -364711185;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "mainType:" + MainType + ","
        + "type:" + Type + ","
        + "name:" + Name + ","
        + "weaponUnlock:" + WeaponUnlock + ","
        + "talentTree:" + Luban.StringUtil.CollectionToString(TalentTree) + ","
        + "}";
    }
}
}

