
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Character
{
public sealed partial class TbLvData : Luban.BeanBase
{
    public TbLvData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["lv"].IsNumber) { throw new SerializationException(); }  Lv = _buf["lv"]; }
        { if(!_buf["exp"].IsNumber) { throw new SerializationException(); }  Exp = _buf["exp"]; }
        { if(!_buf["talentPoint"].IsNumber) { throw new SerializationException(); }  TalentPoint = _buf["talentPoint"]; }
    }

    public static TbLvData DeserializeTbLvData(JSONNode _buf)
    {
        return new Character.TbLvData(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Lv;
    /// <summary>
    /// 升级经验花费
    /// </summary>
    public readonly int Exp;
    /// <summary>
    /// 天赋点
    /// </summary>
    public readonly int TalentPoint;
   
    public const int __ID__ = 183394759;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "lv:" + Lv + ","
        + "exp:" + Exp + ","
        + "talentPoint:" + TalentPoint + ","
        + "}";
    }
}
}

