
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Character
{
/// <summary>
/// 天赋-04
/// </summary>
public partial class TbTalentData
{
    private readonly System.Collections.Generic.Dictionary<int, Character.TalentData> _dataMap;
    private readonly System.Collections.Generic.List<Character.TalentData> _dataList;
    
    public TbTalentData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Character.TalentData>(count);
        _dataList = new System.Collections.Generic.List<Character.TalentData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Character.TalentData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Config.Character.TalentData.DeserializeTalentData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Character.TalentData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Character.TalentData> DataList => _dataList;

    public Character.TalentData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Character.TalentData Get(int key) => _dataMap[key];
    public Character.TalentData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

