
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.Character
{ 
    [System.Flags]
    public enum Weapon
    {
        /// <summary>
        /// 直剑
        /// </summary>
        Sword = 1,
        /// <summary>
        /// 斧
        /// </summary>
        Axe = 2,
        /// <summary>
        /// 锤
        /// </summary>
        Mace = 4,
        /// <summary>
        /// 匕首
        /// </summary>
        Dagger = 8,
        /// <summary>
        /// 杖
        /// </summary>
        Scepter = 16,
        /// <summary>
        /// 矛
        /// </summary>
        Spear = 32,
        /// <summary>
        /// 盾
        /// </summary>
        Shield = 64,
        /// <summary>
        /// 法典
        /// </summary>
        Tome = 128,
        /// <summary>
        /// 法器
        /// </summary>
        Artifact = 256,
        /// <summary>
        /// 远程
        /// </summary>
        Ranged = 512,
        /// <summary>
        /// 巨剑
        /// </summary>
        GreatSword = 1024,
        /// <summary>
        /// 巨斧
        /// </summary>
        GreatAxe = 2048,
        /// <summary>
        /// 巨锤
        /// </summary>
        GreatMace = 4096,
        /// <summary>
        /// 长矛
        /// </summary>
        GreatSpear = 8192,
        /// <summary>
        /// 重型远程
        /// </summary>
        TwoHandedRanged = 16384,
    }

} 

