
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config
{
public partial class GameGlobal
{

     private readonly TbGlobal _data;

     public TbGlobal Data => _data;

    public GameGlobal(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = global::Game.Config.TbGlobal.DeserializeTbGlobal(_buf[0]);  }
    }


    /// <summary>
    /// 版本
    /// </summary>
     public UnityEngine.Vector4 Version => _data.Version;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

