
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace Game.Config
{
public partial class Tables
{
    public GameGlobal GameGlobal {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        GameGlobal = new GameGlobal(loader("gameglobal"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GameGlobal.ResolveRef(this);
    }
}

}

