
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace Game.Config
{
public partial class Tables
{
    public GameGlobal GameGlobal {get; }
    /// <summary>
    /// 增减益Buff-02
    /// </summary>
    public Battle.TbBuffData TbBuffData {get; }
    /// <summary>
    /// 效果-01
    /// </summary>
    public Battle.TbEffectData TbEffectData {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        GameGlobal = new GameGlobal(loader("gameglobal"));
        TbBuffData = new Battle.TbBuffData(loader("battle_tbbuffdata"));
        TbEffectData = new Battle.TbEffectData(loader("battle_tbeffectdata"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GameGlobal.ResolveRef(this);
        TbBuffData.ResolveRef(this);
        TbEffectData.ResolveRef(this);
    }
}

}

