
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config
{
public sealed partial class TbGlobal : Luban.BeanBase
{
    public TbGlobal(JSONNode _buf) 
    {
        { if(!_buf["version"].IsObject) { throw new SerializationException(); }  Version = global::Game.Config.vector4.Deserializevector4(_buf["version"]);  }
    }

    public static TbGlobal DeserializeTbGlobal(JSONNode _buf)
    {
        return new TbGlobal(_buf);
    }

    /// <summary>
    /// 版本
    /// </summary>
    public readonly vector4 Version;
   
    public const int __ID__ = -715958319;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "version:" + Version + ","
        + "}";
    }
}
}

