
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------


local enums =
{
    ---@class Battle.Attribute
     ---@field public Health integer @生命
     ---@field public Attack integer @攻击
     ---@field public Defence integer @防御
     ---@field public Accuracy integer @精准
     ---@field public Dexterity integer @敏捷
    ['Battle.Attribute'] = {   Health=1,  Attack=2,  Defence=3,  Accuracy=4,  Dexterity=5,  };
    ---@class Battle.Blackboard
     ---@field public poisonBase integer @基础毒伤害
    ['Battle.Blackboard'] = {   poisonBase=1,  };
    ---@class Battle.DamageSource
     ---@field public Main integer @主要伤害
     ---@field public Derivation integer @派生伤害
     ---@field public Bounce integer @反弹伤害
    ['Battle.DamageSource'] = {   Main=1,  Derivation=2,  Bounce=3,  };
    ---@class Battle.DamageType
     ---@field public Physical integer @物理伤害
     ---@field public Magical integer @魔法伤害
    ['Battle.DamageType'] = {   Physical=1,  Magical=2,  };
    ---@class Battle.Tag
     ---@field public ImmuneAllDamage integer @免疫所有伤害
     ---@field public Dead integer @死亡
    ['Battle.Tag'] = {   ImmuneAllDamage=1,  Dead=2,  };
}

local beans = {}

local tables =
{
}

return { enums = enums, beans = beans, tables = tables }

