
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------


local enums =
{
    ---@class Battle.Attribute
     ---@field public health integer @生命
     ---@field public attack integer @攻击
    ['Battle.Attribute'] = {   health=1,  attack=2,  };
    ---@class Battle.Blackboard
     ---@field public poisonBase integer @基础毒伤害
    ['Battle.Blackboard'] = {   poisonBase=1,  };
    ---@class Battle.DamageSource
     ---@field public Main integer @主要伤害
     ---@field public Derivation integer @派生伤害
     ---@field public Bounce integer @反弹伤害
    ['Battle.DamageSource'] = {   Main=1,  Derivation=2,  Bounce=3,  };
    ---@class Battle.DamageType
     ---@field public Physical integer @物理伤害
     ---@field public Magical integer @魔法伤害
    ['Battle.DamageType'] = {   Physical=1,  Magical=2,  };
    ---@class Battle.Tag
     ---@field public nondamageable integer @免疫伤害
    ['Battle.Tag'] = {   nondamageable=1,  };
}

local beans = {}

local tables =
{
}

return { enums = enums, beans = beans, tables = tables }

