
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Logic
{
public sealed partial class EffectHurt : Logic.EffectParamBase
{
    public EffectHurt(JSONNode _buf)  : base(_buf) 
    {
    }

    public static EffectHurt DeserializeEffectHurt(JSONNode _buf)
    {
        return new Logic.EffectHurt(_buf);
    }

   
    public const int __ID__ = 960999952;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

