
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Logic
{
public abstract partial class EffectParamBase : Luban.BeanBase
{
    public EffectParamBase(JSONNode _buf) 
    {
    }

    public static EffectParamBase DeserializeEffectParamBase(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "EffectAttack": return new Logic.EffectAttack(_buf);
            case "EffectHurt": return new Logic.EffectHurt(_buf);
            case "EffectInputMove": return new Logic.EffectInputMove(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

