
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Logic
{
public sealed partial class Effect : Luban.BeanBase
{
    public Effect(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["order"].IsNumber) { throw new SerializationException(); }  Order = _buf["order"]; }
    }

    public static Effect DeserializeEffect(JSONNode _buf)
    {
        return new Logic.Effect(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 执行序列
    /// </summary>
    public readonly int Order;
   
    public const int __ID__ = 444811873;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "order:" + Order + ","
        + "}";
    }
}
}

