
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace Game.Config.Logic
{
/// <summary>
/// 实体效果-100
/// </summary>
public partial class TbEffect
{
    private readonly System.Collections.Generic.Dictionary<int, Logic.Effect> _dataMap;
    private readonly System.Collections.Generic.List<Logic.Effect> _dataList;
    
    public TbEffect(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Logic.Effect>(count);
        _dataList = new System.Collections.Generic.List<Logic.Effect>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Logic.Effect _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Game.Config.Logic.Effect.DeserializeEffect(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Logic.Effect> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Logic.Effect> DataList => _dataList;

    public Logic.Effect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Logic.Effect Get(int key) => _dataMap[key];
    public Logic.Effect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

